export const SET_ENTITY = "SET_ENTITY";
export const SET_PIZZA_NAME = "SET_PIZZA_NAME";
export const SET_PIZZA_DOUGH = "SET_PIZZA_DOUGH";
export const SET_PIZZA_SIZE = "SET_PIZZA_SIZE";
export const SET_PIZZA_SAUCE = "SET_PIZZA_SAUCE";
export const SET_PIZZA_INGREDIENT = "SET_PIZZA_INGREDIENT";
export const MOVE_PIZZA_INGREDIENT = "MOVE_PIZZA_INGREDIENT";
