export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const UPDATE_CART_DELIVERY = "UPDATE_CART_DELIVERY";
export const UPDATE_CART_PHONE = "UPDATE_CART_PHONE";
export const UPDATE_CART_ADDRESS = "UPDATE_CART_ADDRESS";
